### ISSUE TITLE
Issues with Roto Command

### ISSUE THREAD

**Issue by Jerry12798** [chrisparsons83/FFDiscordBot#127]
So it seems the Roto Command is no longer working properly. No matter the Player I search for it says, "There is no player found with that name.".. Even if I go to Rotoworld's Website and find the player with the most recent story, and use their name.

**Comment by chrisparsons83** [comment]
Working on this with cp/rotoworld-fix branch. It's getting there, just need to handle the people with multiple names more gracefully. I should have something in there hopefully this weekend.

**Comment by chrisparsons83** [comment]
This should be resolved, kind of. At least the best I can handle it right now. Using headless chrome to get the pages now since there's javascript loading happening on the page after the DOM is rendered. This means the query is slow (like multiple seconds kind of slow) but it does actually return data again.
